import os
import logging
from typing import List, Dict

logger = logging.getLogger(__name__)

class IncidentRoomGenerator:
    def __init__(self):
        # We can configure this via environment variables
        self.provider = os.getenv("LLM_PROVIDER", "local")
        self.api_key = os.getenv("OPENAI_API_KEY", "")
        
    def generate_incident_room(self, cluster_id: str, complaints: List[Dict]) -> str:
        """
        Generates an AI summary of a critical incident based on a cluster of complaints.
        """
        if len(complaints) < 3:
            return "Cluster too small to generate incident room."
            
        texts = [c.get('text', '') for c in complaints]
        combined_text = "\n- ".join(texts[:10]) # Limit to 10 for context window
        
        prompt = f"""
        You are an AI Incident Manager for Sentitron CampusPulse.
        Analyze the following student complaints that have been clustered together:
        
        - {combined_text}
        
        Generate a structured Incident Room Report with:
        1. Executive Summary
        2. Root Cause Hypothesis
        3. Escalation Urgency (Low/Medium/High/Critical)
        4. Recommended Immediate Actions
        """
        
        if self.provider == "openai" and self.api_key:
            return self._call_openai(prompt)
        else:
            return self._call_local_mock(prompt)
            
    def _call_openai(self, prompt: str) -> str:
        try:
            import openai
            openai.api_key = self.api_key
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except ImportError:
            logger.error("openai package not installed.")
            return "Error: OpenAI integration failed."
        except Exception as e:
            logger.error(f"OpenAI API Error: {e}")
            return f"Error: {e}"
            
    def _call_local_mock(self, prompt: str) -> str:
        # Since running a large LLM locally requires significant resources, 
        # this serves as a mock fallback unless a local inference server (like vLLM) is configured.
        return """
        # Incident Room Report (Generated by Local Mock)
        
        **Executive Summary:**
        Multiple reports indicate a localized issue based on the complaint cluster.
        
        **Root Cause Hypothesis:**
        Systemic failure related to infrastructure or academic scheduling.
        
        **Escalation Urgency:**
        High
        
        **Recommended Immediate Actions:**
        1. Dispatch technical/admin team to investigate.
        2. Issue a campus-wide broadcast to acknowledge the issue.
        """

# Singleton instance
llm_room_generator = IncidentRoomGenerator()
