apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campuspulse-ingress
  namespace: campuspulse
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: campuspulse.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: campuspulse-backend
                port:
                  number: 8000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: campuspulse-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: campuspulse-frontend
                port:
                  number: 3000
