"use client";

import React, { useState, useEffect } from 'react';
import { Network, TrendingUp, ShieldAlert, Cpu } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { formatToIST } from '@/lib/utils';
import { apiFetch } from '@/lib/api';
import ProtectedRoute from '@/components/auth/ProtectedRoute';

const CLUSTER_HISTORY = [
  { time: 'Day 1', volume: 2 },
  { time: 'Day 2', volume: 5 },
  { time: 'Day 3', volume: 15 },
  { time: 'Day 4', volume: 45 },
  { time: 'Day 5', volume: 120 },
  { time: 'Today', volume: 215 },
];

interface Cluster {
  cluster_id: string;
  representative_text: string;
  max_urgency: number;
  incident_count: number;
}

function ClustersExplorer() {
  const [activeClusters, setActiveClusters] = useState<Cluster[]>([]);
  const [generating, setGenerating] = useState(false);

  const handleGenerateReport = () => {
    setGenerating(true);
    setTimeout(() => {
      const reportContent = `
SENTITRON CAMPUSPULSE
OFFICIAL AI CLUSTER REPORT
========================================
CLUSTER ID: CLSTR-WIFI-092
SEVERITY: CRITICAL ESCALATION
AFFECTED DEPARTMENTS: CSE, ECE, ME

AI SUMMARY:
AI has detected a massive semantic surge in complaints regarding network connectivity exclusively in the Main Library area during final exam preparations.

RECOMMENDED ACTIONS:
- Dispatch IT infrastructure team to Main Library Router Node A. 
- Send mass notification to students regarding estimated downtime.

Generated by AI Intelligence Engine on ${formatToIST(new Date())}
`;
      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'CampusPulse_Report_CLSTR-WIFI-092.txt';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setGenerating(false);
    }, 1500);
  };

  useEffect(() => {
    const fetchClusters = () => {
      apiFetch('/api/clusters/active')
        .then(res => res.json())
        .then(data => {
          if (Array.isArray(data)) {
            setActiveClusters(data);
          } else {
            console.error("Expected active clusters array but got:", data);
          }
        })
        .catch(err => console.error(err));
    };

    fetchClusters();
    const interval = setInterval(fetchClusters, 3000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="p-8 max-w-[1600px] mx-auto min-h-screen">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Network className="w-8 h-8 text-purple-500" />
          <h1 className="text-3xl font-bold tracking-tight">Incident Intelligence Explorer</h1>
        </div>
        <p className="text-slate-400">Deep semantic exploration of AI-generated incident clusters.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Active Cluster Detail */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-slate-900/40 backdrop-blur-md border border-rose-500/30 rounded-2xl p-8 relative overflow-hidden shadow-[0_0_30px_rgba(244,63,94,0.05)]">
            <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none">
              <ShieldAlert className="w-48 h-48 text-rose-500" />
            </div>
            
            <div className="flex items-center gap-3 mb-4">
              <span className="px-3 py-1 text-xs font-bold tracking-widest text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded shadow-[0_0_10px_rgba(244,63,94,0.2)]">CRITICAL ESCALATION</span>
              <span className="text-slate-500 text-sm font-mono">ID: CLSTR-WIFI-092</span>
            </div>
            
            <h2 className="text-3xl font-bold text-slate-100 mb-2">Main Library Wi-Fi Outage</h2>
            <p className="text-slate-400 max-w-2xl text-lg mb-8">
              AI has detected a massive semantic surge in complaints regarding network connectivity exclusively in the Main Library area during final exam preparations.
            </p>

            <div className="grid grid-cols-3 gap-4 mb-8">
              <div className="bg-slate-950/50 border border-slate-800 p-4 rounded-xl">
                <div className="text-slate-500 text-sm mb-1">Detected Complaints</div>
                <div className="text-3xl font-light text-rose-400">215</div>
              </div>
              <div className="bg-slate-950/50 border border-slate-800 p-4 rounded-xl">
                <div className="text-slate-500 text-sm mb-1">Departments Affected</div>
                <div className="text-lg font-medium text-slate-200">CSE, ECE, ME</div>
              </div>
              <div className="bg-slate-950/50 border border-slate-800 p-4 rounded-xl">
                <div className="text-slate-500 text-sm mb-1">Escalation Velocity</div>
                <div className="text-lg font-medium text-rose-400 flex items-center gap-2">
                  <TrendingUp className="w-5 h-5" /> +450% / hr
                </div>
              </div>
            </div>

            <div className="h-64 w-full">
              <h3 className="text-sm font-semibold text-slate-400 mb-4 uppercase tracking-wider">Cluster Evolution Timeline</h3>
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={CLUSTER_HISTORY}>
                  <defs>
                    <linearGradient id="colorVol" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#f43f5e" stopOpacity={0.3}/>
                      <stop offset="95%" stopColor="#f43f5e" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                  <XAxis dataKey="time" stroke="#475569" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis stroke="#475569" fontSize={12} tickLine={false} axisLine={false} />
                  <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#1e293b' }} />
                  <Area type="monotone" dataKey="volume" stroke="#f43f5e" strokeWidth={3} fillOpacity={1} fill="url(#colorVol)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* Right Column: Related Clusters & Actions */}
        <div className="space-y-6">
          <div className="bg-slate-900/40 backdrop-blur-md border border-slate-800 rounded-2xl p-6">
            <h3 className="text-lg font-semibold tracking-tight mb-4 flex items-center gap-2">
              <Cpu className="w-5 h-5 text-blue-400" /> AI Recommendations
            </h3>
            <ul className="space-y-4">
              <li className="bg-blue-500/10 border border-blue-500/20 p-4 rounded-xl text-blue-100 text-sm leading-relaxed">
                <strong className="block text-blue-400 mb-1">Immediate Action Required:</strong>
                Dispatch IT infrastructure team to Main Library Router Node A. Send mass notification to students regarding estimated downtime.
              </li>
              <li className="bg-slate-950 border border-slate-800 p-4 rounded-xl text-slate-300 text-sm leading-relaxed">
                <strong className="block text-slate-400 mb-1">Historical Correlation:</strong>
                Similar surge detected in Nov 2025. Root cause was thermal throttling of the core switch.
              </li>
            </ul>
            <button 
              onClick={handleGenerateReport}
              disabled={generating}
              className="w-full mt-4 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-800 disabled:text-blue-300 text-white font-semibold py-2.5 rounded-xl transition-colors flex justify-center items-center gap-2"
            >
              {generating ? (
                <>
                  <div className="w-4 h-4 border-2 border-blue-300 border-t-transparent rounded-full animate-spin" />
                  Generating...
                </>
              ) : (
                'Generate Official Report'
              )}
            </button>
          </div>

          <div className="bg-slate-900/40 backdrop-blur-md border border-slate-800 rounded-2xl p-6">
            <h3 className="text-lg font-semibold tracking-tight mb-4">Other Emerging Clusters</h3>
            <div className="space-y-3">
              {activeClusters.slice(0, 5).map(c => (
                <div key={c.cluster_id} className="flex justify-between items-center p-3 bg-slate-950/50 border border-slate-800 rounded-lg hover:border-slate-600 cursor-pointer transition-colors">
                  <div className="flex flex-col overflow-hidden mr-2">
                    <span className="text-sm text-slate-300 truncate" title={c.cluster_id}>{c.cluster_id}</span>
                    <span className="text-xs text-slate-500 truncate">{c.representative_text}</span>
                  </div>
                  <span className={`px-2 py-0.5 text-xs font-bold rounded border shrink-0 ${c.max_urgency >= 4 ? 'text-rose-400 bg-rose-500/10 border-rose-500/20' : 'text-blue-400 bg-blue-500/10 border-blue-500/20'}`}>{c.incident_count}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ClustersExplorerWrapper() {
  return (
    <ProtectedRoute allowedRoles={["admin", "moderator"]}>
      <ClustersExplorer />
    </ProtectedRoute>
  );
}
